### ISSUE TITLE
wg-ui-and-a11y Status Update 2020-12-02

### ISSUE THREAD

**Issue by rebeccanthomas** [ampproject/wg-components#68] opened 2020-12-02 21:32 UTC
## What was accomplished

-  Design doc for `amp-render` completed, design review on 12/02 
-  Code complete for Serving NPA ads (publishing in Q1 2021
-  `amp-ima-video` bugfixes
-  `amp-fit-text` accessibility fix in review

## What's next

-  Begin implementing `amp-render` after getting feedback from design review
-  Begin design for `amp-list` v2
-  Working on finalizing design for granular consent
-  Working on e2e test for `amp-fit-text` a11y update
-  Update from GA4 team coming 12/4

**Comment by jaygray0919** [comment] 2020-12-03 09:28
Any chance to influence `amp-list` v2? We have a previously reported issue that might be a candidate for resolution in V2.

**Comment by samouri** [comment] 2020-12-07 18:43
> We have a previously reported issue that might be a candidate for resolution in V2.

Which issue? Can you link to it? Is it a candidate for being fixed in V1 as well?

**Comment by jaygray0919** [comment] 2020-12-08 14:33
@samouri Here it is: https://github.com/ampproject/amphtml/issues/23675
The WaPo link is broken. But the idea is simple. Think this way: a dictionary of terms, one endpoint for each term. Then, for a given page, use only the term needed for (a paragraph). We might use one structure on many pages. The WaPo implementation was an image and the player performance stats. Rather than managing one structure of all players, and then using a hop operator to localize the specific player for display (via `amp-mustache`), the WaPo design was `one player : one end-point`. This approach is similar to the PubChem approach for chemicals. I can fetch the specific chemical i need; do not have to load the entire PubChem endpoint and then hop to the target chemical. But `amp-list` cannot be used inline (e.g. in a span) as it forces a line break.

Our request: remove the line-break caused by `amp-list`. Then we can build dictionaries of terms, not have to have a dictionary of all terms.

**Comment by jaygray0919** [comment] 2020-12-11 11:22
@samouri Here is another (suspect) issue with amp/state/list/mustache: https://github.com/ampproject/amphtml/issues/31532
It appears that some CSS can break amp/state/list/mustache injection and formatting. Do you see a user error in the third example?

**Closed** 2021-10-11 17:55 UTC
Labels: Type: Status Update
